name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
   runs-on: macos-11
   env:
    THEOS: theos
   steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Theos
        run: |
          /bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/lint/f706db1e0fd0075e80bb7121c05d5f02/raw/e273471213214b6b794141df7817786ec063fced/install_theos.sh)"
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build
        run: |
          export THEOS=~/theos
          chmod +x compile.command
          bash compile.command
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
         name: CheatManager.ipa
         path: "CheatManager.ipa"
