name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Install Theos
        uses: Randomblock1/theos-action@v1
      - name: Build
        run: | 
          export THEOS=$GITHUB_WORKSPACE/theos
          cd $GITHUB_WORKSPACE
          chmod +x compile.command
          bash compile.command
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
          name: CheatManager.ipa
          path: "CheatManager.ipa"
